spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:./db
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
